"""Orchestrator: load config -> load state -> fetch -> evaluate -> notify -> save state.

Run hourly by .github/workflows/wind-check.yml. For each subscriber's named
alert, looks at the rolling forecast window (now through +3 days) and tracks
whether it's currently "on" (at least one qualifying hour somewhere in that
window) or "off". A notification only fires on a state TRANSITION:

- off -> on: send the flyable-window digest, remember it's on.
- on -> off: send a "condition no longer available" notice, forget it.
- on -> on / off -> off: nothing changed, stay quiet.

This replaces the old once-per-calendar-day dedup, which only looked at
"today" and could never tell the subscriber when a window disappeared.

Sites (coordinates) live in docs/sites.json, generated by sync_sites.py from
the "Sitios propuestos" sheet (approved rows only) — see MANUAL.md. Subscribers
(email + their own layer thresholds) live in the SUBSCRIBERS_JSON secret, since
the repo is public and subscriber emails shouldn't be.
"""
import argparse
import json
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).parent))

from fetch_forecast import collect_points, fetch_forecast
from notify import (
    build_cleared_body,
    build_email_body,
    build_telegram_text,
    cleared_subject_line,
    send_email,
    send_telegram,
    subject_line,
)
from rules import evaluate_layers
from state import load_state, prune_stale, save_state, state_key

ROOT = Path(__file__).resolve().parent.parent
SITES_PATH = ROOT / "docs" / "sites.json"
STATE_PATH = ROOT / "state" / "sent_log.json"
FORECAST_DAYS = 3


def local_now_str(site):
    tz = ZoneInfo(site["timezone"])
    return datetime.now(tz).strftime("%Y-%m-%dT%H:%M")


def load_subscribers():
    raw = os.environ.get("SUBSCRIBERS_JSON")
    if not raw:
        return {}
    return json.loads(raw)


def send_to_subscriber(subscriber, subject, body, smtp_user, smtp_password, telegram_token, site_id, label):
    email = subscriber.get("email")
    chat_id = subscriber.get("telegram_chat_id")
    sent = False
    if email:
        if smtp_user and smtp_password:
            send_email(subject, body, smtp_user, smtp_password, email)
            sent = True
        else:
            print(f"[{site_id}] {label}: GMAIL_USER/GMAIL_APP_PASSWORD not set, skipping email", file=sys.stderr)
    if chat_id:
        if telegram_token:
            send_telegram(telegram_token, chat_id, build_telegram_text(subject, body))
            sent = True
        else:
            print(f"[{site_id}] {label}: TELEGRAM_BOT_TOKEN not set, skipping Telegram", file=sys.stderr)
    return sent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Evaluate and print, but never send email or write state")
    args = parser.parse_args()

    sites = json.loads(SITES_PATH.read_text(encoding="utf-8"))
    subscribers_by_site = load_subscribers()

    state = load_state(STATE_PATH)
    original_state = dict(state)
    valid_keys = set()

    points = collect_points(sites)
    try:
        forecast = fetch_forecast(points, forecast_days=FORECAST_DAYS)
    except Exception as exc:  # noqa: BLE001 - single free API, fail loudly, no retry logic needed for v1
        print(f"ERROR fetching Open-Meteo forecast: {exc}", file=sys.stderr)
        sys.exit(1)

    smtp_user = os.environ.get("GMAIL_USER")
    smtp_password = os.environ.get("GMAIL_APP_PASSWORD")
    telegram_token = os.environ.get("TELEGRAM_BOT_TOKEN")

    for site in sites:
        site_id = site["id"]
        subscribers = subscribers_by_site.get(site_id, [])
        if not subscribers:
            print(f"[{site_id}] no subscribers, skipping")
            continue

        now_str = local_now_str(site)
        points_hourly = {
            point_name: forecast[(site_id, point_name)]["hourly"]
            for point_name in site["points"]
        }

        for subscriber in subscribers:
            email = subscriber.get("email")
            chat_id = subscriber.get("telegram_chat_id")
            alert_name = subscriber.get("alert_name")
            identity = email or (f"telegram:{chat_id}" if chat_id else None)
            if not identity:
                print(f"[{site_id}] subscriber {subscriber.get('name', '?')!r} has neither email nor telegram_chat_id, skipping", file=sys.stderr)
                continue
            label = f"{identity}#{alert_name}" if alert_name else identity

            key = state_key(site_id, label)
            valid_keys.add(key)

            try:
                hourly_results = evaluate_layers(subscriber["layers"], site, points_hourly)
            except Exception as exc:  # noqa: BLE001 - one bad subscriber entry must not break everyone else's run
                print(f"[{site_id}] ERROR evaluating {label}: {exc}", file=sys.stderr)
                continue

            # Rolling window: only hours from right now through the end of
            # the fetched forecast (today onward, not the whole of today).
            qualifying = [h for h in hourly_results if h["time"] >= now_str and h["passed"]]

            currently_on = bool(qualifying)
            previously_on = key in state

            if currently_on and not previously_on:
                subject = subject_line(site, len(qualifying), alert_name)
                body = build_email_body(site, qualifying, subscriber["layers"], subscriber.get("name"), alert_name)
                action = "ALERT ON"
            elif not currently_on and previously_on:
                subject = cleared_subject_line(site, alert_name)
                body = build_cleared_body(site, subscriber.get("name"), alert_name)
                action = "ALERT CLEARED"
            else:
                print(f"[{site_id}] {label}: sin cambio (on={currently_on})")
                continue

            if args.dry_run:
                print(f"[{site_id}] WOULD SEND ({action}) to {label}:\nSubject: {subject}\n{body}\n")
                continue

            sent = send_to_subscriber(subscriber, subject, body, smtp_user, smtp_password, telegram_token, site_id, label)
            if not sent:
                continue

            print(f"[{site_id}] sent {action} to {label}")
            if currently_on:
                state[key] = {
                    "since": datetime.now(ZoneInfo(site["timezone"])).isoformat(),
                    "qualifying_hours": [h["time"] for h in qualifying],
                }
            else:
                del state[key]

    if not args.dry_run:
        state = prune_stale(state, valid_keys)
        if state != original_state:
            save_state(STATE_PATH, state)


if __name__ == "__main__":
    main()
